name: Parse TOML Python Version and Install it
description: "This action reads the Python version from a pyproject.toml file and installs the specified version of Python using the setup-python action."
inputs:
  ref_reference:
    description: "The git reference to check out"
    required: false
    default: ${{ github.ref }}
outputs:
  python-version:
    description: "The Python version to install"
    value: ${{ steps.get-python.outputs.python-version }}

runs:
  using: "composite"
  steps:
    - name: Grab Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref_reference }}

    - name: Extract Python Version
      id: get-python
      shell: bash
      run: |
        # More robust Python version extraction
        PYTHON_VERSION=$(grep -E '^python\s*=\s*"' pyproject.toml | \
          sed -E 's/.*python\s*=\s*"([^"]+)".*/\1/' | \
          sed -E 's/[~^<>=]+//g' | \
          grep -E '^[0-9]+\.[0-9]+(\.[0-9]+)?$')

        # Validate extracted version
        if [[ ! "$PYTHON_VERSION" =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
          echo "Error: Invalid Python version format"
          exit 1
        fi

        echo "Extracted Python version: $PYTHON_VERSION"
        echo "python-version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
        echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.get-python.outputs.python-version }}

    - name: Cache Poetry installation
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-${{ runner.os }}-1.8.5

    - name: Install Poetry
      shell: bash
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      run: |
        curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.8.5 python3 -

    - name: Add Poetry to PATH
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify Python Version
      shell: bash
      run: |
        python --version
        python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"
